import {
  InteractionRequiredAuthError,
  PublicClientApplication,
  type AccountInfo,
  type AuthenticationResult
} from '@azure/msal-browser';
import { authServer, clientId, entra, redirectUri, scope, storageKeys } from './config';
import type { TokenResponse } from './types';

export const msalInstance = new PublicClientApplication({
  auth: {
    clientId: entra.clientId,
    authority: entra.authority,
    redirectUri: entra.redirectUri
  },
  cache: {
    cacheLocation: 'sessionStorage'
  }
});

const msalReady = msalInstance.initialize();

export async function startLogin() {
  // Local IdP PKCE values are generated by the SPA, but the password is entered only on AuthServer.
  const verifier = base64UrlEncode(crypto.getRandomValues(new Uint8Array(32)));
  const challenge = await createCodeChallenge(verifier);
  const state = base64UrlEncode(crypto.getRandomValues(new Uint8Array(16)));
  const nonce = base64UrlEncode(crypto.getRandomValues(new Uint8Array(16)));

  sessionStorage.setItem(storageKeys.provider, 'local');
  sessionStorage.setItem(storageKeys.verifier, verifier);
  sessionStorage.setItem(storageKeys.state, state);
  sessionStorage.setItem(storageKeys.nonce, nonce);

  const authorizeUrl = new URL(`${authServer}/connect/authorize`);
  authorizeUrl.searchParams.set('response_type', 'code');
  authorizeUrl.searchParams.set('client_id', clientId);
  authorizeUrl.searchParams.set('redirect_uri', redirectUri);
  authorizeUrl.searchParams.set('scope', scope);
  authorizeUrl.searchParams.set('state', state);
  authorizeUrl.searchParams.set('nonce', nonce);
  authorizeUrl.searchParams.set('code_challenge', challenge);
  authorizeUrl.searchParams.set('code_challenge_method', 'S256');

  window.location.assign(authorizeUrl.toString());
}

export async function startEntraLogin() {
  // MSAL owns Entra's authorization code + PKCE details, token cache, state, and nonce.
  sessionStorage.setItem(storageKeys.provider, 'entra');
  await msalReady;
  await msalInstance.loginRedirect({
    scopes: [...entra.apiScopes]
  });
}

export async function initializeAuthState() {
  const entraResult = await tryCompleteEntraLoginCallback();
  if (entraResult) {
    return entraResult;
  }

  if (window.location.pathname === '/callback') {
    return completeLocalLoginCallback();
  }

  return restoreEntraSession();
}

export async function completeLoginCallback() {
  const provider = sessionStorage.getItem(storageKeys.provider);

  if (provider !== 'local') {
    const entraResult = await tryCompleteEntraLoginCallback();
    if (entraResult) {
      return entraResult;
    }
  }

  if (provider === 'entra') {
    throw new Error('Entra callback was not found. Open the app at http://localhost:5173 before starting Entra login.');
  }

  return completeLocalLoginCallback();
}

export async function getApiToken(tokens: TokenResponse) {
  if (tokens.provider !== 'entra') {
    return tokens;
  }

  const result = await acquireEntraToken([...entra.apiScopes]);
  const tokenResponse = toTokenResponse(result, 'entra');
  localStorage.setItem(storageKeys.tokens, JSON.stringify(tokenResponse));
  return tokenResponse;
}

export async function getGraphAccessToken() {
  const result = await acquireEntraToken([...entra.graphScopes]);
  return result.accessToken;
}

export async function restoreEntraSession() {
  await msalReady;
  const account = msalInstance.getActiveAccount() ?? msalInstance.getAllAccounts()[0];
  if (!account) {
    return null;
  }

  msalInstance.setActiveAccount(account);
  const result = await msalInstance.acquireTokenSilent({
    account,
    scopes: [...entra.apiScopes]
  });
  const tokenResponse = toTokenResponse(result, 'entra');
  localStorage.setItem(storageKeys.tokens, JSON.stringify(tokenResponse));
  return tokenResponse;
}

async function tryCompleteEntraLoginCallback() {
  await msalReady;
  const result = await msalInstance.handleRedirectPromise();

  if (!result) {
    return null;
  }

  window.history.replaceState({}, document.title, '/');

  if (result.account) {
    msalInstance.setActiveAccount(result.account);
  }

  const tokenResponse = toTokenResponse(result, 'entra');
  localStorage.setItem(storageKeys.tokens, JSON.stringify(tokenResponse));
  return tokenResponse;
}

async function completeLocalLoginCallback() {
  const params = new URLSearchParams(window.location.search);
  const code = params.get('code');
  const returnedState = params.get('state');
  const expectedState = sessionStorage.getItem(storageKeys.state);
  const verifier = sessionStorage.getItem(storageKeys.verifier);
  const expectedNonce = sessionStorage.getItem(storageKeys.nonce);

  window.history.replaceState({}, document.title, '/');

  if (!code || !verifier || !expectedState || returnedState !== expectedState) {
    throw new Error('Callback validation failed.');
  }

  const body = new URLSearchParams({
    grant_type: 'authorization_code',
    client_id: clientId,
    code,
    redirect_uri: redirectUri,
    code_verifier: verifier
  });

  const response = await fetch(`${authServer}/connect/token`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded'
    },
    body
  });

  if (!response.ok) {
    throw new Error(`Token exchange failed: HTTP ${response.status}`);
  }

  const tokenResponse = (await response.json()) as TokenResponse;
  tokenResponse.provider = 'local';
  const idTokenPayload = tokenResponse.id_token ? decodeJwtPayload(tokenResponse.id_token) : null;

  if (idTokenPayload?.nonce !== expectedNonce) {
    throw new Error('Nonce validation failed.');
  }

  localStorage.setItem(storageKeys.tokens, JSON.stringify(tokenResponse));
  return tokenResponse;
}

export function clearSession() {
  localStorage.removeItem(storageKeys.tokens);
  sessionStorage.removeItem(storageKeys.provider);
  sessionStorage.removeItem(storageKeys.verifier);
  sessionStorage.removeItem(storageKeys.state);
  sessionStorage.removeItem(storageKeys.nonce);
  void msalReady.then(() => msalInstance.clearCache());
}

export function readTokens() {
  return readJson<TokenResponse>(storageKeys.tokens);
}

export function decodeJwtPayload(token: string): Record<string, unknown> | null {
  const [, payload] = token.split('.');
  if (!payload) {
    return null;
  }

  const padded = payload.replace(/-/g, '+').replace(/_/g, '/').padEnd(Math.ceil(payload.length / 4) * 4, '=');
  return JSON.parse(atob(padded)) as Record<string, unknown>;
}

async function acquireEntraToken(scopes: string[]) {
  await msalReady;
  const account = getActiveAccount();

  try {
    const result = await msalInstance.acquireTokenSilent({
      account,
      scopes
    });
    msalInstance.setActiveAccount(result.account);
    return result;
  } catch (error) {
    if (error instanceof InteractionRequiredAuthError) {
      await msalInstance.acquireTokenRedirect({
        account,
        scopes
      });
    }

    throw error;
  }
}

function getActiveAccount(): AccountInfo {
  const account = msalInstance.getActiveAccount() ?? msalInstance.getAllAccounts()[0];
  if (!account) {
    throw new Error('No Entra account found. Sign in with Entra first.');
  }

  msalInstance.setActiveAccount(account);
  return account;
}

function toTokenResponse(result: AuthenticationResult, provider: 'entra'): TokenResponse {
  return {
    provider,
    access_token: result.accessToken,
    id_token: result.idToken,
    token_type: result.tokenType || 'Bearer',
    expires_in: result.expiresOn
      ? Math.max(0, Math.floor((result.expiresOn.getTime() - Date.now()) / 1000))
      : 0,
    scope: result.scopes.join(' ')
  };
}

async function createCodeChallenge(verifier: string) {
  const data = new TextEncoder().encode(verifier);
  const digest = await crypto.subtle.digest('SHA-256', data);
  return base64UrlEncode(new Uint8Array(digest));
}

function base64UrlEncode(bytes: Uint8Array) {
  const binary = Array.from(bytes, (byte) => String.fromCharCode(byte)).join('');
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
}

function readJson<T>(key: string): T | null {
  const value = localStorage.getItem(key);
  return value ? (JSON.parse(value) as T) : null;
}
